dist: bionic
language: go
branches:
  only:
    - main
go:
- "1.15"
script:
- go build ./...
- go test -race -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
- bash <(curl -s https://codecov.io/bash)